from typing import Protocol, Optional, List 
from sqlmodel import Session 
from app.models.trips import Trips
from app.models.transactions import Transactions
from app.models.students import Students
from app.models.registrations import Registrations


class TripRepository(Protocol):
    def get(self, session: Session, trip_id: int) -> Optional[Trips]: ...
    def list(self, session: Session) -> List[Trips]: ...
    def create(self, session: Session, trip: Trips) -> Trips: ...

class RegistrationRepository(Protocol):
    def get(self, session: Session, reg_id: int) -> Optional[Registrations]: ...
    def find_by_trip_student(self, session: Session, trip_id: int, student_id: int) -> Optional["Registrations"]: ...
    def create(self, session: Session, reg: "Registrations", student: "Students") -> "Registrations": ...

class TransactionRepository(Protocol):
    def create(self, session: Session, tx: "Transactions") -> "Transactions": ...
    def update(self, session: Session, tx: "Transactions") -> "Transactions": ...
    def get_by_id(self, session: Session, tx_id: int) -> Optional["Transactions"]: ...
    def get_by_idempotency(self, session: Session, key: str) -> Optional["Transactions"]: ...

class StudentRepository(Protocol):
    def get(self, session: Session, student_id: int) -> Optional[Students]: ...
    def create(self, session: Session, student: Students) -> Students: ...